### ISSUE TITLE
API source?

### ISSUE THREAD

**Issue by ralfeus** [suapapa/go_postkr#2]
Not an issue but a question. I'm looking for Korea Post API for getting parcel price for a shipping. Does anything like that exist?

**Comment by suapapa** [comment]
Sorry to say, I can't find it in API form.

But, `epost.go.kr` provide following pracel price calcurator on the web;

    http://service.epost.go.kr/comm/search/cmsc01003.jsp

**Comment by ralfeus** [comment]
Ok, thank you. That would do.

Respectfuly
Mykhaylo Khodorev
